enum BaseClass {
    DEVICE_PRE_CLASS_CODE = 0x00,
    MASS_STORAGE_CONTROLLER = 0x01,
    NETWORK_CONTROLLER = 0x02,
    DISPLAY_CONTROLLER = 0x03,
    MULTIMEDIA_DEVICE = 0x04,
    MEMORY_CONTROLLER = 0x05,
    BRIDGE_DEVICE = 0x06,
    SIMPLE_COMMUNICATION_CONTROLLERS = 0x07,
    BASE_SYSTEM_PERIPHERALS = 0x08,
    INPUT_DEVICES = 0x09,
    DOCKING_STATIONS = 0x0A,
    PROCESSORS = 0x0B,
    SERIAL_BUS_CONTROLLERS = 0x0C,
    WIRELESS_CONTROLLER = 0x0D,
    INTELLIGENT_IO_CONTROLLERS = 0x0E,
    SATELLITE_COMMUNICATION_CONTROLLERS = 0x0F,
    ENCRYPTION_DECRYPTION_CONTROLLERS = 0x10,
    DATA_ACQUISITION_SIGNAL_PROCESSING_CONTROLLERS = 0x11,
    PROCESSING_ACCELERATORS = 0x12,
    NON_ESSENTIAL_INSTRUMENTATION = 0x13,
    // 0x14 - 0xFE are reserved
    DEVICE_DOES_NOT_FIT = 0xFF
};